import test from 'node:test';import assert from 'node:assert/strict';
import {modules} from '../src/content.js';
import {lessonPool,vocabularyPool,selectSession,numberReading,frameContexts,trackAnswer} from '../src/engine.js';
import {correct,freshState,validState} from '../src/core.js';
function rng(seed){return ()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};}
test('generated corpus is internally consistent and supports diverse tasks',()=>{let total=0;for(const m of modules){for(const u of [...m.lessons,...m.mcos]){const pool=u.words?vocabularyPool(u):lessonPool(u,m);total+=pool.length;assert.ok(pool.length>=10,u.id);assert.equal(pool.length,new Set(pool.map(q=>q.id)).size,u.id);for(const q of pool){assert.ok(q.answer&&q.explanation&&q.prompt);assert.ok(!q.prompt.includes('{'));if(q.type==='choice'){assert.ok(q.choices.includes(q.answer));assert.equal(q.choices.filter(a=>correct(q,a)).length,1,q.id);assert.equal(q.choices.length,new Set(q.choices).size);}if(q.type==='order')assert.equal(q.tokens.join(''),q.answer);assert.ok(correct(q,q.answer));}const session=selectSession(pool,{random:rng(42)});assert.ok(new Set(session.map(q=>q.type)).size>=2,u.id);for(const q of session)if(q.choices){assert.ok(q.choices.length<=4);assert.ok(q.choices.includes(q.answer));}}}assert.ok(total>1500);});
test('immediate repetition is avoided while unseen variants remain',()=>{const pool=lessonPool(modules[0].lessons[0],modules[0]);const first=selectSession(pool,{random:rng(42)});const recent=first.map(q=>q.id);const second=selectSession(pool,{recent,random:rng(42)});assert.ok(second.every(q=>!recent.includes(q.id)));});
test('mandatory vocabulary sessions cover every word once with changing forms',()=>{for(const m of modules)for(const c of m.mcos){const pool=vocabularyPool(c);const first=selectSession(pool,{count:c.words.length,coverConcepts:true,random:rng(42)});assert.equal(first.length,c.words.length);assert.equal(new Set(first.map(q=>q.conceptId)).size,c.words.length);const second=selectSession(pool,{count:c.words.length,coverConcepts:true,recent:first.map(q=>q.id),random:rng(42)});assert.ok(second.every(q=>!first.some(x=>x.id===q.id)));}});
test('kana sessions prioritize unmastered sounds without duplicating a concept',()=>{const u=modules[0].lessons[0],pool=lessonPool(u,modules[0]);const pending=[`${u.id}:q:3`,`${u.id}:q:9`];const qs=selectSession(pool,{count:10,coverConcepts:true,unmastered:pending});assert.equal(qs.length,2);assert.ok(qs.every(q=>pending.includes(q.masteryId)));});
test('phonetic equivalents never appear as competing correct kana options',()=>{const u=modules[0].lessons[2];for(const q of lessonPool(u,modules[0]).filter(q=>q.id.endsWith(':recognize'))){const reading=u.table.find(x=>x[0]===q.answer)[1];assert.ok(q.choices.filter(c=>u.table.find(x=>x[0]===c)?.[1]===reading).length===1);}});
test('numbers are compositional and handle tens exactly',()=>{assert.equal(numberReading(0),'れい');assert.equal(numberReading(10),'じゅう');assert.equal(numberReading(20),'にじゅう');assert.equal(numberReading(47),'よんじゅうなな');assert.equal(numberReading(99),'きゅうじゅうきゅう');assert.throws(()=>numberReading(100));});
test('grammar combinations preserve existence rules and accepted phrase orders',()=>{const m=modules.find(m=>m.id==='m4'),u=m.lessons.find(l=>l.id==='existence');for(const c of frameContexts(u)){if(c.tokens.includes('ねこ')||c.tokens.includes('いぬ')||c.tokens.includes('ともだち'))assert.equal(c.tokens.at(-1),'います');else assert.equal(c.tokens.at(-1),'あります');assert.equal(c.tokens[1],'に');assert.equal(c.tokens[3],'が');}const q=lessonPool(u,m).find(q=>q.type==='order');assert.ok(correct(q,q.alternatives[0]));assert.ok(correct(q,q.tokens.join(' ')));});
test('answer history prioritizes errors and stays bounded without invalidating v0.1 saves',()=>{const s=freshState();assert.ok(validState(s));const pool=vocabularyPool(modules[0].mcos[0]);for(let i=0;i<100;i++)trackAnswer(s,{id:'exercise-'+i,conceptId:'concept'},false);assert.equal(s.recentQuestions.length,80);assert.ok(validState(s));trackAnswer(s,{id:'corrected',conceptId:'concept'},true);assert.equal(s.exerciseStats.concept.wrong,99);const q=pool.find(q=>q.type==='input');const picked=selectSession(pool,{count:1,stats:{[q.conceptId]:{right:0,wrong:3}},random:rng(1)});assert.equal(picked[0].conceptId,q.conceptId);});
