name: kotoba
publish_to: none
description: Apprentissage du japonais en français, sur Android et Windows.
version: 0.3.1+4
environment:
  sdk: '>=3.8.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  shared_preferences: 2.5.5
  file_picker: 13.1.0
  flutter_tts: 4.2.5
  url_launcher: 6.3.3
  unorm_dart: 0.3.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/curriculum.json
    - assets/app_icon.png
  fonts:
    - family: KotobaJapanese
      fonts:
        - asset: assets/fonts/KotobaJapanese.ttf
