import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
romaji='a i u e o ka ki ku ke ko sa shi su se so ta chi tsu te to na ni nu ne no ha hi fu he ho ma mi mu me mo ya yu yo ra ri ru re ro wa wo n'.split()
hira=list('あいうえおかきくけこさしすせそたちつてとなにぬねのはひふへほまみむめもやゆよらりるれろわをん')
kata=list('アイウエオカキクケコサシスセソタチツテトナニヌネノハヒフヘホマミムメモヤユヨラリルレロワヲン')
def q(prompt,answer,explanation,alternatives=[]): return dict(prompt=prompt,answer=answer,explanation=explanation,alternatives=alternatives)
def lesson(id,title,paragraphs,questions,video=None,table=None): return dict(id=id,title=title,paragraphs=paragraphs,questions=questions,video=video,table=table)
def words(id,title,rows):return dict(id=id,title=title,words=[dict(id=f'{id}-{i}',writing=w,reading=r,meaning=m) for i,(w,r,m) in enumerate(rows)])
modules=[dict(id='m1',title='Hiragana & katakana',subtitle='Tes premiers pas dans l’écriture japonaise',symbol='あ',color='coral',lessons=[
 lesson('hiragana','Lire les hiragana',['Les hiragana représentent des sons, généralement une consonne et une voyelle. あ se lit a, か se lit ka. Apprends-les par petites familles, puis mélange-les pour éviter de mémoriser seulement leur ordre.','Les hiragana servent notamment à écrire les terminaisons grammaticales et les particules. Ne cherche pas à traduire un kana isolé : il représente un son.'],[q(f'Lis ce hiragana : {h}',r,f'{h} se lit « {r} ».') for h,r in zip(hira,romaji)],'https://www.youtube.com/watch?v=_PCJnq_-oT8',list(zip(hira,romaji))),
 lesson('katakana','Lire les katakana',['Les katakana représentent les mêmes sons que les hiragana. Ils servent notamment aux mots empruntés à d’autres langues, comme カメラ (kamera), appareil photo.','Attention aux paires proches : シ / ツ et ソ / ン. Observe l’orientation et entraîne-toi à les reconnaître dans des mots.'],[q(f'Lis ce katakana : {h}',r,f'{h} se lit « {r} ».') for h,r in zip(kata,romaji)],None,list(zip(kata,romaji))),
 lesson('sounds','Accents, combinaisons & pauses',['Les deux petits traits (dakuten) modifient certains sons : か → が (ka → ga), さ → ざ (sa → za). Le petit cercle transforme les sons de la famille h en p : は → ぱ.','Un petit ゃ, ゅ ou ょ s’associe au kana précédent : きゃ (kya), しゅ (shu), ちょ (cho).','Le petit っ marque une fermeture brève avant la consonne suivante : きって se lit kitte. En katakana, ー prolonge la voyelle précédente : コーヒー (kōhī). En hiragana, l’allongement s’écrit avec une voyelle ; おう est souvent prononcé comme un o long.'],[q('Lis が','ga','Les dakuten transforment ka en ga.'),q('Lis ぱ','pa','Le petit cercle transforme ha en pa.'),q('Lis きゃ','kya','Le petit ゃ forme un son combiné.'),q('Lis きって','kitte','Le petit っ double ici la consonne t.'),q('Lis コーヒー','koohii','ー allonge la voyelle précédente.',['kōhī','kouhii']),q('Lis しゅ','shu','し + petit ゅ se lit shu.')])],mcos=[
 words('m1-life','Les mots du quotidien',[('ねこ','ねこ','chat'),('いぬ','いぬ','chien'),('みず','みず','eau'),('そら','そら','ciel'),('やま','やま','montagne'),('はな','はな','fleur'),('かさ','かさ','parapluie'),('くつ','くつ','chaussures')]),
 words('m1-loans','Les mots en katakana',[('カメラ','カメラ','appareil photo'),('テレビ','テレビ','télévision'),('ラジオ','ラジオ','radio'),('バス','バス','bus'),('パン','パン','pain'),('コーヒー','コーヒー','café'),('ホテル','ホテル','hôtel'),('タクシー','タクシー','taxi')])]),
 dict(id='m2',title='Arabiasūji & premiers kanji',subtitle='Compter et découvrir les caractères de sens',symbol='一',color='sage',lessons=[
 lesson('numbers','Les nombres de 0 à 10',['Les arabiasūji sont les chiffres arabes : 0, 1, 2… Ils sont courants au Japon. Les kanji numériques constituent une autre manière d’écrire les nombres.','Pour commencer, retiens les lectures ci-dessous. 4 peut se lire よん ou し, 7 なな ou しち et 9 きゅう ou く. Le choix dépend du contexte ; utilise ici よん, なな et きゅう.'],[q(f'Écris en hiragana le nombre {i}',r,f'{i} se lit {r}.', {'0':['ぜろ'],'4':['し'],'7':['しち'],'9':['く']}.get(str(i),[])) for i,r in enumerate(['れい','いち','に','さん','よん','ご','ろく','なな','はち','きゅう','じゅう'])],'https://www.youtube.com/watch?v=-a8A0Bf3sxo',[(str(i),r) for i,r in enumerate(['れい','いち','に','さん','よん','ご','ろく','なな','はち','きゅう','じゅう'])]),
 lesson('kanji','Un kanji, plusieurs lectures',['Un kanji porte du sens et peut avoir plusieurs lectures. Apprends la lecture d’un mot dans son contexte plutôt qu’une liste de lectures isolées.','Dans ce module, dix mots seulement sont présentés en kanji, répartis entre les deux MCO. La lecture en kana reste visible pendant l’apprentissage. Dans les autres exemples du module, les nombres restent écrits en chiffres arabes.'],[q('Que porte principalement un kanji ?','du sens','Les kanji portent du sens ; leur lecture dépend du mot.',['sens']),q('Un kanji a-t-il toujours une seule lecture ?','non','Un même kanji peut avoir plusieurs lectures.')])],mcos=[
 words('m2-nature','Nature · 5 mots en kanji',[('山','やま','montagne'),('川','かわ','rivière'),('水','みず','eau'),('火','ひ','feu'),('空','そら','ciel')]),
 words('m2-world','Autour de soi · 5 mots en kanji',[('人','ひと','personne'),('口','くち','bouche'),('目','め','œil'),('手','て','main'),('本','ほん','livre')])]),
 dict(id='m3',title='Les particules de base',subtitle='Construire et comprendre tes premières phrases',symbol='は',color='blue',lessons=[
 lesson('topic','は, の & も',['Une particule indique le rôle d’un mot ou d’un groupe dans la phrase. は marque le thème et se prononce wa dans cet emploi. わたしは がくせいです signifie « Je suis étudiant(e) ».','の relie deux noms : わたしの ほん = mon livre. も signifie ici « aussi » : わたしも がくせいです = moi aussi, je suis étudiant(e).','です termine poliment une phrase nominale. Dans ces exercices, le vocabulaire nécessaire est donné dans les MCO.'],[q('Complète « Je suis étudiant(e) » : わたし＿がくせいです','は','は marque le thème : moi.'),q('Complète « mon livre » : わたし＿ほん','の','の relie le possesseur au nom.'),q('Complète « Moi aussi, je suis étudiant(e) » : わたし＿がくせいです','も','も ajoute le sens « aussi ».'),q('Comment se prononce は comme particule ?','wa','は se prononce wa quand elle marque le thème.',['わ'])],'https://www.youtube.com/watch?v=z9dU8wwFEEs'),
 lesson('action','を, に & で',['を marque le complément d’objet direct : みずを のみます = je bois de l’eau. Cette particule se prononce généralement o.','に peut indiquer une destination : がっこうに いきます = je vais à l’école. で indique ici le lieu d’une action : がっこうで べんきょうします = j’étudie à l’école.','Les particules ont plusieurs emplois. Ce module travaille uniquement ces premiers usages. Lis le sens de la phrase avant de choisir.'],[q('Complète « Je bois de l’eau » : みず＿のみます','を','を marque ce qui est bu.'),q('Complète « Je vais à l’école » : がっこう＿いきます','に','に indique ici la destination.'),q('Complète « J’étudie à l’école » : がっこう＿べんきょうします','で','で indique le lieu où se déroule l’action.'),q('Comment se prononce généralement を ?','o','La particule を se prononce généralement o.',['お'])])],mcos=[
 words('m3-people','Personnes & lieux',[('わたし','わたし','je / moi'),('がくせい','がくせい','étudiant'),('せんせい','せんせい','professeur'),('ともだち','ともだち','ami'),('がっこう','がっこう','école'),('いえ','いえ','maison'),('ほん','ほん','livre'),('みず','みず','eau')]),
 words('m3-verbs','Premières actions',[('のみます','のみます','boire (forme polie)'),('たべます','たべます','manger (forme polie)'),('いきます','いきます','aller (forme polie)'),('みます','みます','voir (forme polie)'),('よみます','よみます','lire (forme polie)'),('べんきょうします','べんきょうします','étudier (forme polie)')])])]
from curriculum import enrich
modules = enrich(modules, lesson, words)
(root/'src/content.js').write_text('// Contenu pédagogique original. Régénération : python3 scripts/content.py\nexport const modules = '+json.dumps(modules,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
