import {lessonPool,vocabularyPool,selectSession,trackAnswer,frameContexts} from './engine.js';
import {modules} from './content.js';
import {PASS,correct,freshState,validState,required,ready,unlocked,schedule,shuffle,wordQuestions,examQuestions,score,recordExam,localDate,streak} from './core.js';
const KEY='kotoba.progress.v1';
let state=freshState(), storageAvailable=true, installPrompt;
try {const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(validState(parsed))state=parsed;else notify('La sauvegarde est incompatible. Tu peux importer une sauvegarde valide.');}} catch {storageAvailable=false;}
const main=document.querySelector('main');
let session=null;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function notify(text){const toast=document.querySelector('#toast');toast.textContent=text;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),5000);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));storageAvailable=true;}catch{storageAvailable=false;notify('Sauvegarde indisponible. Exporte ton carnet avant de fermer.');}updateCounts();}
function activity(){const date=localDate();state.activity[date]=(state.activity[date]||0)+1;}
function complete(id){if(!state.completed.includes(id)) state.completed.push(id);save();}
function allWords(){return modules.flatMap((m,i)=>unlocked(i,modules,state)?m.mcos.filter(v=>state.completed.includes(v.id)).flatMap(v=>v.words):[]);}
function dueWords(){return allWords().filter(w=>!state.cards[w.id]||state.cards[w.id].due<=Date.now());}
function updateCounts(){document.querySelector('#review-count').textContent=dueWords().length||'';}
function button(label,action,extra=''){return `<button ${extra} data-action="${action}">${label}</button>`;}
function heading(kicker,title,subtitle){return `<div class="page-heading"><p class="eyebrow">${kicker}</p><h1>${title}</h1><p class="muted">${subtitle}</p></div>`;}
function moduleCard(m,i){const open=unlocked(i,modules,state), n=required(m).filter(id=>state.completed.includes(id)).length, total=required(m).length, pass=(state.exams[m.id]?.score??0)>=PASS;return `<a class="module-card ${m.color} ${open?'':'locked'}" href="#module/${m.id}" ${open?'': 'aria-label="Module verrouillé : réussir le module précédent"'}><span class="module-symbol" lang="ja">${m.symbol}</span><div><p class="eyebrow">MODULE 0${i+1} ${pass?'· VALIDÉ':open?'· À TON RYTHME':'· VERROUILLÉ'}</p><h2>${m.title}</h2><p>${m.subtitle}</p><div class="progress" role="progressbar" aria-label="Progression du module" aria-valuenow="${n}" aria-valuemin="0" aria-valuemax="${total}"><i style="width:${n/total*100}%"></i></div><small>${n}/${total} étapes · ${m.mcos.length} MCO · 1 DS</small></div><span class="arrow">${open?'↗':'♧'}</span></a>`;}
function home(){const nextIndex=modules.findIndex(m=>(state.exams[m.id]?.score??0)<PASS),i=nextIndex<0?modules.length-1:nextIndex,m=modules[i], today=state.activity[localDate()]||0;
main.innerHTML=heading('こんにちは · BONJOUR','Le japonais commence<br>par un petit pas.','Lis, pratique, puis retrouve les mots au bon moment.')+`<section class="hero"><div><span class="pill">TON PROCHAIN CHAPITRE · MODULE 0${i+1}</span><h2>${m.title}</h2><p>${m.subtitle}. Une leçon, quelques mots, et tu avances.</p><a class="button primary" href="#module/${m.id}">Continuer mon parcours <span>→</span></a></div><div class="paper-art" aria-hidden="true"><span class="sun"></span><span class="vertical" lang="ja">日本語</span><span class="stamp" lang="ja">学</span><span class="art-note">NIHONGO<br>LE PLAISIR D’APPRENDRE</span></div></section><section class="stats"><article><span class="stat-icon">✦</span><strong>${streak(state.activity)}</strong><span>jours de suite</span></article><article><span class="stat-icon">◎</span><strong>${today} / ${state.goal}</strong><span>réponses aujourd’hui</span></article><article><span class="stat-icon">↻</span><strong>${dueWords().length}</strong><span>mots à revoir</span></article></section><div class="section-heading"><h2>Ton chemin d’apprentissage</h2><a href="#path">Voir le parcours →</a></div>${moduleCard(m,i)}<section class="two-col"><article class="panel"><p class="eyebrow">LA MÉMOIRE SE CULTIVE</p><h2>Un mot revu, un mot retenu.</h2><p>Les cartes reviennent selon ta facilité à les retrouver. Sans course, sans vies perdues.</p><a href="#review" class="text-link">Réviser mes mots →</a></article><article class="panel source-panel"><p class="eyebrow">RESSOURCES VIDÉO</p><h2>Une leçon, aussi en vidéo.</h2><p>Retrouve les cours de Julien Fontanier en complément des fiches et exercices de Kotoba.</p><a href="https://www.youtube.com/@coursdejaponais" target="_blank" rel="noopener" class="text-link">Cours de japonais ! ↗</a></article></section>`;}
function path(){main.innerHTML=heading('PAS À PAS','Mon parcours','Chaque module réunit des leçons, des MCO obligatoires et un DS.')+modules.map(moduleCard).join('')+`<p class="footnote">Un MCO contient au plus 10 mots. Termine les leçons et les MCO, puis obtiens ${PASS} % au DS pour ouvrir le module suivant.</p>`;}
function modulePage(id){const i=modules.findIndex(m=>m.id===id);if(i<0)return missing();const m=modules[i];if(!unlocked(i,modules,state)){main.innerHTML=heading('ENCORE UN PETIT PAS','Ce module attend son tour.','Réussis le DS du module précédent pour continuer.')+`<a href="#module/${modules[i-1].id}" class="button primary">Retour au module précédent</a>`;return;}
const row=(u,type)=>`<a class="unit" href="#${type}/${m.id}/${u.id}"><span class="unit-icon">${state.completed.includes(u.id)?'✓':type==='mco'?'言':'▤'}</span><div><small>${type==='mco'?`MCO OBLIGATOIRE · ${u.words.length} MOTS`:'LEÇON + EXERCICES'}</small><h3>${u.title}</h3></div><span>→</span></a>`;
main.innerHTML=`<a href="#path" class="back">← Le parcours</a>`+heading(`MODULE 0${i+1}`,m.title,m.subtitle)+`<h2 class="section-title">Comprendre & pratiquer</h2>${m.lessons.map(l=>row(l,'lesson')).join('')}<h2 class="section-title">Mes MCO · le vocabulaire essentiel</h2>${m.mcos.map(l=>row(l,'mco')).join('')}<section class="exam-panel"><div><p class="eyebrow">LE POINT SUR TES ACQUIS</p><h2>DS de fin de module</h2><p>Sans aide pendant le test. Corrections détaillées à la fin. Objectif : ${PASS} %.</p>${state.exams[id]?`<small>Meilleur score : ${state.exams[id].score} % · Dernier : ${state.exams[id].lastScore??state.exams[id].score} %</small>`:''}</div>${button('Passer le DS →',`exam:${id}`,ready(m,state)?'class="primary"':'disabled')}<small>${ready(m,state)?'Tu as terminé toutes les étapes.':'Termine toutes les leçons et tous les MCO pour passer le DS.'}</small></section>`;}
function unitPage(type,id,unitId){const index=modules.findIndex(m=>m.id===id),m=modules[index];if(!m||!unlocked(index,modules,state))return modulePage(id);const u=(type==='lesson'?m.lessons:m.mcos).find(l=>l.id===unitId);if(!u)return missing();
main.innerHTML=`<a href="#module/${id}" class="back">← ${m.title}</a>`+heading(type==='lesson'?'COMPRENDRE AVANT DE PRATIQUER':'MODULE COMPLÉMENTAIRE OBLIGATOIRE',u.title,type==='lesson'?'Lis la fiche, puis entraîne-toi.':'Lis les mots et leurs lectures, puis vérifie ce que tu as retenu.')+(type==='lesson'?`<article class="lesson-content panel">${u.paragraphs.map(p=>`<p>${p}</p>`).join('')}${u.generator?.kind==='frames'?`<h3>Exemples & vocabulaire de cette leçon</h3><div class="example-list">${frameContexts(u).filter((c,i)=>i%Math.max(1,Math.floor(frameContexts(u).length/4))===0).slice(0,4).map(c=>`<p><strong lang="ja">${esc(c.japanese)}</strong><br>${esc(c.french)}</p>`).join('')}</div><details><summary>Voir le lexique utilisé dans les exercices</summary>${[...new Map(u.generator.frames.flatMap(f=>Object.values(f.domains).flat()).map(w=>[w.jp,w])).values()].map(w=>`<p><span lang="ja">${esc(w.jp)}</span> · ${esc(w.fr)}</p>`).join('')}</details>`:''}${u.table?`<div class="kana-grid">${u.table.map(([w,r])=>`<div><strong lang="ja">${w}</strong><small>${r}</small></div>`).join('')}</div>`:''}</article>${u.resources.map(r=>`<a class="resource" href="${r.url}" target="_blank" rel="noopener">▷ ${esc(r.title)} · Cours de japonais ! ↗</a>`).join('')}`:`<div class="word-list">${u.words.map(w=>`<article><div><strong lang="ja">${w.writing}</strong><span lang="ja">${w.reading}</span></div><p>${w.meaning}</p>${button('Écouter',`speak:${w.id}`,'class="quiet" aria-label="Écouter '+esc(w.reading)+'"')}</article>`).join('')}</div>`)+`<div class="start-practice panel"><div><h2>À toi de jouer.</h2><p>${type==='lesson'?'Jusqu’à 10 défis variés : lecture, compréhension et reconstruction. Les sons sont validés progressivement ; les autres leçons demandent 80 %.':'Chaque mot est testé. Obtiens 80 % pour terminer ce MCO.'}</p>${type==='lesson'&&u.generator?.kind==='kana'?`<p>${u.table.filter((q,i)=>state.completed.includes(`${u.id}:q:${i}`)).length}/${u.table.length} sons déjà reconnus.</p>`:''}</div>${button('Commencer les exercices →',`practice:${type}:${id}:${unitId}`,'class="primary"')}</div>`;}
function startPractice(type,moduleId,unitId){const m=modules.find(x=>x.id===moduleId),u=(type==='lesson'?m.lessons:m.mcos).find(x=>x.id===unitId);
const pool=type==='mco'?vocabularyPool(u):lessonPool(u,m);
const isKana=u.generator?.kind==='kana';
const pending=isKana?u.table.map((q,i)=>`${u.id}:q:${i}`).filter(id=>!state.completed.includes(id)):null;
const questions=selectSession(pool,{count:type==='mco'?u.words.length:10,recent:state.recentQuestions,stats:state.exerciseStats,coverConcepts:type==='mco'||isKana,unmastered:pending});
session={kind:'practice',type,moduleId,unitId,questions,answers:[],index:0,checked:false};renderSession();}
function startExam(id){const m=modules.find(m=>m.id===id);if(!ready(m,state)||!unlocked(modules.indexOf(m),modules,state))return;session={kind:'exam',moduleId:id,questions:examQuestions(m,Math.random,state.recentQuestions),answers:[],index:0,checked:false};renderSession();}
function renderSession(){session.selectedTokens=[];const s=session,q=s.questions[s.index];main.innerHTML=`<a href="#module/${s.moduleId}" class="back">← Quitter la séance (progression conservée à la fin)</a>`+heading(s.kind==='exam'?'DS · SANS CORRECTION INTERMÉDIAIRE':'ENTRAÎNEMENT',s.kind==='exam'?'Fais le point.':'À ton rythme.','Suis la consigne : écris, choisis une réponse ou remets les éléments dans l’ordre.')+`<div class="session-progress"><span>Question ${s.index+1} / ${s.questions.length}</span><div class="progress"><i style="width:${s.index/s.questions.length*100}%"></i></div></div><section class="question panel" data-question-id="${esc(q.id)}"><p class="question-prompt" lang="ja">${esc(q.prompt)}</p><form id="answer-form">${q.type==='choice'?'<span>Choisis une réponse</span>':'<label for="answer">Ta réponse</label>'}${q.type==='choice'?`<div class="choices">${q.choices.map((v,i)=>`<button type="button" data-action="choose:${i}">${esc(v)}</button>`).join('')}</div>`:''}${q.type==='order'?`<div class="token-bank">${q.displayTokens.map(t=>`<button type="button" data-action="token:${t.index}">${esc(t.text)}</button>`).join('')}</div>${button('Recommencer l’ordre','clear-order','type="button" class="quiet"')}`:''}<input type="${q.type==='choice'?'hidden':'text'}" id="answer" name="answer" autocomplete="off" autocapitalize="off" spellcheck="false" ${q.type==='input'?'required':'readonly'} placeholder="${q.type==='order'?'Ta phrase apparaîtra ici':q.type==='choice'?'Choisis une réponse ci-dessus':'Écris ta réponse'}"><button class="primary" type="submit">${s.kind==='exam'?'Enregistrer et continuer':'Vérifier ma réponse'}</button></form><div id="feedback" role="status"></div></section>`;document.querySelector('#answer-form').addEventListener('submit',submitAnswer);document.querySelector(q.type==='choice'?'.choices button':q.type==='order'?'.token-bank button':'#answer').focus();}
function submitAnswer(e){e.preventDefault();const s=session;if(s.checked)return;const value=document.querySelector('#answer').value;if(!value.trim())return;s.answers[s.index]=value;const question=s.questions[s.index];trackAnswer(state,question,correct(question,value));activity();save();if(s.kind==='exam')return nextQuestion();s.checked=true;const q=s.questions[s.index],ok=correct(q,value);if(ok&&q.masteryId){if(!state.completed.includes(q.masteryId))state.completed.push(q.masteryId);save();}
document.querySelector('#answer').disabled=true;document.querySelector('#answer-form button').disabled=true;document.querySelector('#feedback').innerHTML=`<div class="feedback ${ok?'success':'retry'}"><strong>${ok?'Bien joué !':'On le retient pour la prochaine fois.'}</strong><p>Réponse : <b>${esc(q.answer)}</b></p><p>${esc(q.explanation)}</p>${button(s.index===s.questions.length-1?'Voir mon bilan':'Question suivante →','next','class="primary"')}</div>`;document.querySelector('[data-action="next"]').focus();}
function nextQuestion(){if(++session.index<session.questions.length){session.checked=false;renderSession();}else finishSession();}
function finishSession(){const s=session,m=modules.find(m=>m.id===s.moduleId),result=score(s.questions,s.answers);let completed=false,detail='';
if(s.kind==='exam'){recordExam(state,m,result);completed=result>=PASS;save();detail=completed?'Module validé ! Tu peux poursuivre ton parcours.':'Revois les corrections et entraîne-toi avant une nouvelle tentative.';}
else {const u=(s.type==='lesson'?m.lessons:m.mcos).find(u=>u.id===s.unitId);completed=s.type==='lesson'&&u.generator?.kind==='kana'?u.table.every((q,i)=>state.completed.includes(`${u.id}:q:${i}`)):result>=PASS;if(completed)complete(u.id);detail=completed?'Étape validée. Continue avec la suivante.':s.type==='lesson'&&u.generator?.kind==='kana'?'Les prochaines séances ciblent les sons encore à apprendre, avec des questions différentes.':'Atteins 80 % pour valider cette étape.';}
main.innerHTML=heading('TON BILAN',`${result} % · ${completed?'Bravo !':'Tu progresses.'}`,detail)+`<section class="panel results">${s.questions.map((q,i)=>`<article class="${correct(q,s.answers[i])?'correct':'incorrect'}"><span>${correct(q,s.answers[i])?'✓':'↻'}</span><div><h3>${esc(q.prompt)}</h3><p>Ta réponse : ${esc(s.answers[i])} · Attendu : <b>${esc(q.answer)}</b></p><p>${esc(q.explanation)}</p></div></article>`).join('')}</section><div class="actions"><a class="button primary" href="#module/${m.id}">Retour au module →</a>${s.kind==='practice'?button('Une autre séance',`practice:${s.type}:${m.id}:${s.unitId}`):button('Refaire le DS',`exam:${m.id}`)}</div>`;session=null;}
let reviewQueue=[], reviewWord=null,reviewRevealed=false;
function review(){const due=dueWords();main.innerHTML=heading('RETROUVER, C’EST APPRENDRE','Mes révisions',`${allWords().length} mots débloqués · ${due.length} à revoir maintenant.`)+`<section class="panel review-intro"><span class="large-mark" lang="ja">言</span><h2>${due.length?'Tes mots t’attendent.':'Ton carnet respire.'}</h2><p>${due.length?'Essaie de retrouver la lecture et le sens avant de retourner la carte. Évalue ensuite ton rappel.':'Termine un MCO pour ajouter ses mots, ou reviens quand tes cartes seront dues.'}</p>${due.length?button('Réviser maintenant →','review-start','class="primary"'):'<a class="button primary" href="#path">Aller au parcours →</a>'}</section><p class="footnote">« À revoir » : 10 minutes. Les autres réponses espacent les rappels selon tes résultats. Les lectures restent toujours disponibles au verso.</p>`;}
function renderReview(){reviewWord=reviewQueue.shift();reviewRevealed=false;if(!reviewWord){main.innerHTML=heading('SÉANCE TERMINÉE','Bien joué, à bientôt.','Tes réponses ont programmé les prochains rappels.')+'<a href="#review" class="button primary">Mon carnet de révision →</a>';return;}main.innerHTML=`<a href="#review" class="back">← Quitter les révisions</a>`+heading('RAPPEL ACTIF',`${reviewQueue.length+1} carte(s) dans cette séance`,'Retrouve la lecture et le sens, puis retourne la carte.')+`<section class="flashcard"><span class="eyebrow">QUELLE LECTURE ? QUEL SENS ?</span><strong lang="ja">${reviewWord.writing}</strong><div id="card-back">${button('Retourner la carte','reveal','class="primary"')}</div></section>`;}
function reveal(){if(!reviewWord||reviewRevealed)return;reviewRevealed=true;document.querySelector('#card-back').innerHTML=`<p class="reading" lang="ja">${reviewWord.reading}</p><p>${reviewWord.meaning}</p>${button('▷ Écouter',`speak:${reviewWord.id}`,'class="quiet"')}<div class="rating">${['À revoir','Difficile','Bien','Facile'].map((text,i)=>button(text,`rate:${i}`)).join('')}</div>`;}
function settings(){main.innerHTML=heading('TON CARNET','Apprendre à ta façon.','Ta progression est enregistrée sur cet appareil. Exporte-la pour la transférer.')+`<section class="panel settings"><h2>Mon objectif quotidien</h2><label for="goal">Réponses par jour</label><select id="goal">${[5,10,15,20,30,50].map(n=>`<option value="${n}" ${state.goal===n?'selected':''}>${n} réponses</option>`).join('')}</select><p>Les erreurs comptent aussi : essayer fait partie de l’apprentissage.</p><h2>Ma sauvegarde</h2><p>${storageAvailable?'Sauvegarde locale active.':'Le stockage est indisponible : exporte ta progression avant de fermer.'} Pas de synchronisation automatique entre appareils.</p><div class="actions">${button('Exporter mon carnet','export')}<label class="button" for="import">Importer un carnet</label><input id="import" type="file" accept="application/json,.json"></div><h2>Installer l’application</h2><p>Sur Android et PC : utilise « Installer l’application » dans le navigateur. Sur iPhone : Safari → Partager → Sur l’écran d’accueil. L’installation nécessite HTTPS ou localhost.</p>${installPrompt?button('Installer Kotoba','install','class="primary"'):''}<h2>Les ressources du parcours</h2><p>Kotoba est un projet indépendant. Les fiches et exercices sont originaux. Les cours vidéo de Julien Fontanier sont proposés via des liens vers sa chaîne ; ils nécessitent Internet.</p><a href="https://www.youtube.com/@coursdejaponais" target="_blank" rel="noopener">Cours de japonais ! ↗</a></section>`;document.querySelector('#goal').addEventListener('change',e=>{state.goal=Number(e.target.value);save();notify('Objectif enregistré.');});document.querySelector('#import').addEventListener('change',async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>2000000)throw Error();const parsed=JSON.parse(await file.text());if(!validState(parsed))throw Error();if(!window.confirm('Remplacer le carnet actuel par cette sauvegarde ?'))return;state=parsed;save();settings();notify('Carnet importé.');}catch{notify('Ce fichier n’est pas une sauvegarde Kotoba valide.');}});}
function speak(id){const word=modules.flatMap(m=>m.mcos.flatMap(v=>v.words)).find(w=>w.id===id);if(!word)return;if(!('speechSynthesis' in window))return notify('La lecture audio n’est pas disponible dans ce navigateur.');const voice=speechSynthesis.getVoices().find(v=>v.lang.startsWith('ja'));if(!voice)return notify('Aucune voix japonaise installée. Ajoute une voix japonaise dans les paramètres de ton appareil.');const utterance=new SpeechSynthesisUtterance(word.reading);utterance.lang='ja-JP';utterance.voice=voice;utterance.rate=0.8;speechSynthesis.cancel();speechSynthesis.speak(utterance);}
function missing(){main.innerHTML=heading('PAGE INTROUVABLE','Retrouvons ton chemin.','')+'<a href="#path" class="button primary">Mon parcours</a>';}
function route(){session=null;reviewWord=null;const [page='home',id,unitId]=(location.hash.slice(1)||'home').split('/');document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===page||(['module','lesson','mco'].includes(page)&&a.dataset.page==='path')));if(page==='home')home();else if(page==='path')path();else if(page==='module')modulePage(id);else if(['lesson','mco'].includes(page))unitPage(page,id,unitId);else if(page==='review')review();else if(page==='settings')settings();else missing();updateCounts();window.scrollTo(0,0);}
document.addEventListener('click',async e=>{const anchor=e.target.closest('a[href^="#"]');if(anchor&&anchor.getAttribute('href')===location.hash){e.preventDefault();route();return;}const b=e.target.closest('[data-action]');if(!b||b.disabled)return;const [a,...args]=b.dataset.action.split(':');if(a==='choose'&&session&&!session.checked){const q=session.questions[session.index];document.querySelector('#answer').value=q.choices[Number(args[0])];document.querySelectorAll('.choices button').forEach((b,i)=>b.classList.toggle('selected',i===Number(args[0])));}if(a==='token'&&session&&!session.checked){const q=session.questions[session.index];session.selectedTokens??=[];const index=Number(args[0]);if(!session.selectedTokens.includes(index)){session.selectedTokens.push(index);b.disabled=true;document.querySelector('#answer').value=session.selectedTokens.map(i=>q.tokens[i]).join('');}}if(a==='clear-order'&&session&&!session.checked){session.selectedTokens=[];document.querySelector('#answer').value='';document.querySelectorAll('.token-bank button').forEach(b=>b.disabled=false);}if(a==='practice')startPractice(...args);if(a==='exam')startExam(args[0]);if(a==='next')nextQuestion();if(a==='review-start'){reviewQueue=shuffle(dueWords()).slice(0,20);renderReview();}if(a==='reveal')reveal();if(a==='rate'&&reviewRevealed){state.cards[reviewWord.id]=schedule(state.cards[reviewWord.id],Number(args[0]));activity();save();renderReview();}if(a==='speak')speak(args[0]);if(a==='export'){const url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download=`kotoba-${localDate()}.json`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}if(a==='install'&&installPrompt){await installPrompt.prompt();installPrompt=null;settings();}});
window.addEventListener('hashchange',route);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;});window.addEventListener('online',()=>document.querySelector('#connection').textContent='Apprentissage local');window.addEventListener('offline',()=>document.querySelector('#connection').textContent='Mode hors ligne');
if(!navigator.onLine)document.querySelector('#connection').textContent='Mode hors ligne';
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>notify('Le mode hors ligne nécessite HTTPS ou localhost.'));
route();
